version: '3'
services: 
  nginx:
    image: 'nginx:1.23'
    ports: 
      - '443:443'
      - '80:80'
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      # - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/default-ssl.conf:/etc/nginx/conf.d/default-ssl.conf
      - ./testhtml:/usr/share/nginx/html/testhtml
      - ./log/:/var/log/nginx/
      - ./cert/:/etc/ssl/additional/
      - ./cert/dhparam.pem:/etc/nginx/dhparam.pem
